/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodType = { 'aNegative' : null } |
  { 'oPositive' : null } |
  { 'abPositive' : null } |
  { 'bPositive' : null } |
  { 'aPositive' : null } |
  { 'oNegative' : null } |
  { 'abNegative' : null } |
  { 'bNegative' : null };
export interface EmergencyContact { 'name' : string, 'phone' : string }
export interface InsuranceInfo {
  'primaryCarePhysician' : string,
  'groupNumber' : string,
  'medicareId' : string,
  'emergencyContacts' : Array<EmergencyContact>,
  'providerName' : string,
  'policyNumber' : string,
}
export interface MedicalHistory {
  'surgeries' : Array<string>,
  'vaccinations' : Array<Vaccination>,
  'diagnoses' : Array<string>,
  'medications' : Array<Medication>,
  'allergies' : Array<string>,
}
export interface Medication {
  'dosage' : string,
  'name' : string,
  'frequency' : string,
}
export interface UserProfile {
  'bloodType' : BloodType,
  'dateOfBirth' : bigint,
  'name' : string,
  'primaryLanguage' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vaccination { 'date' : bigint, 'name' : string }
export interface VisionRecord {
  'prescription' : string,
  'leftEyeAcuity' : string,
  'optometrist' : string,
  'notes' : [] | [string],
  'examDate' : bigint,
  'rightEyeAcuity' : string,
}
export interface VitalReading {
  'readingType' : VitalType,
  'value' : string,
  'note' : [] | [string],
  'unit' : string,
  'timestamp' : bigint,
}
export type VitalType = { 'weight' : null } |
  { 'bloodGlucose' : null } |
  { 'SpO2' : null } |
  { 'temperature' : null } |
  { 'bloodPressure' : null } |
  { 'heartRate' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVitalReading' : ActorMethod<[VitalReading], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVitalReading' : ActorMethod<[bigint], undefined>,
  'getAllVitalReadings' : ActorMethod<[Principal], Array<VitalReading>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInsuranceInfo' : ActorMethod<[Principal], InsuranceInfo>,
  'getLatestVitalReading' : ActorMethod<[Principal, VitalType], VitalReading>,
  'getMedicalHistory' : ActorMethod<[Principal], MedicalHistory>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisionRecord' : ActorMethod<[Principal], VisionRecord>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInsuranceInfo' : ActorMethod<[InsuranceInfo], undefined>,
  'updateMedicalHistory' : ActorMethod<[MedicalHistory], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateVisionRecord' : ActorMethod<[VisionRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];