/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VitalType = IDL.Variant({
  'weight' : IDL.Null,
  'bloodGlucose' : IDL.Null,
  'SpO2' : IDL.Null,
  'temperature' : IDL.Null,
  'bloodPressure' : IDL.Null,
  'heartRate' : IDL.Null,
});
export const VitalReading = IDL.Record({
  'readingType' : VitalType,
  'value' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'unit' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodType = IDL.Variant({
  'aNegative' : IDL.Null,
  'oPositive' : IDL.Null,
  'abPositive' : IDL.Null,
  'bPositive' : IDL.Null,
  'aPositive' : IDL.Null,
  'oNegative' : IDL.Null,
  'abNegative' : IDL.Null,
  'bNegative' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bloodType' : BloodType,
  'dateOfBirth' : IDL.Int,
  'name' : IDL.Text,
  'primaryLanguage' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const InsuranceInfo = IDL.Record({
  'primaryCarePhysician' : IDL.Text,
  'groupNumber' : IDL.Text,
  'medicareId' : IDL.Text,
  'emergencyContacts' : IDL.Vec(EmergencyContact),
  'providerName' : IDL.Text,
  'policyNumber' : IDL.Text,
});
export const Vaccination = IDL.Record({ 'date' : IDL.Int, 'name' : IDL.Text });
export const Medication = IDL.Record({
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const MedicalHistory = IDL.Record({
  'surgeries' : IDL.Vec(IDL.Text),
  'vaccinations' : IDL.Vec(Vaccination),
  'diagnoses' : IDL.Vec(IDL.Text),
  'medications' : IDL.Vec(Medication),
  'allergies' : IDL.Vec(IDL.Text),
});
export const VisionRecord = IDL.Record({
  'prescription' : IDL.Text,
  'leftEyeAcuity' : IDL.Text,
  'optometrist' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'examDate' : IDL.Int,
  'rightEyeAcuity' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVitalReading' : IDL.Func([VitalReading], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVitalReading' : IDL.Func([IDL.Int], [], []),
  'getAllVitalReadings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VitalReading)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInsuranceInfo' : IDL.Func([IDL.Principal], [InsuranceInfo], ['query']),
  'getLatestVitalReading' : IDL.Func(
      [IDL.Principal, VitalType],
      [VitalReading],
      ['query'],
    ),
  'getMedicalHistory' : IDL.Func([IDL.Principal], [MedicalHistory], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisionRecord' : IDL.Func([IDL.Principal], [VisionRecord], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInsuranceInfo' : IDL.Func([InsuranceInfo], [], []),
  'updateMedicalHistory' : IDL.Func([MedicalHistory], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
  'updateVisionRecord' : IDL.Func([VisionRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VitalType = IDL.Variant({
    'weight' : IDL.Null,
    'bloodGlucose' : IDL.Null,
    'SpO2' : IDL.Null,
    'temperature' : IDL.Null,
    'bloodPressure' : IDL.Null,
    'heartRate' : IDL.Null,
  });
  const VitalReading = IDL.Record({
    'readingType' : VitalType,
    'value' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'unit' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodType = IDL.Variant({
    'aNegative' : IDL.Null,
    'oPositive' : IDL.Null,
    'abPositive' : IDL.Null,
    'bPositive' : IDL.Null,
    'aPositive' : IDL.Null,
    'oNegative' : IDL.Null,
    'abNegative' : IDL.Null,
    'bNegative' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bloodType' : BloodType,
    'dateOfBirth' : IDL.Int,
    'name' : IDL.Text,
    'primaryLanguage' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InsuranceInfo = IDL.Record({
    'primaryCarePhysician' : IDL.Text,
    'groupNumber' : IDL.Text,
    'medicareId' : IDL.Text,
    'emergencyContacts' : IDL.Vec(EmergencyContact),
    'providerName' : IDL.Text,
    'policyNumber' : IDL.Text,
  });
  const Vaccination = IDL.Record({ 'date' : IDL.Int, 'name' : IDL.Text });
  const Medication = IDL.Record({
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const MedicalHistory = IDL.Record({
    'surgeries' : IDL.Vec(IDL.Text),
    'vaccinations' : IDL.Vec(Vaccination),
    'diagnoses' : IDL.Vec(IDL.Text),
    'medications' : IDL.Vec(Medication),
    'allergies' : IDL.Vec(IDL.Text),
  });
  const VisionRecord = IDL.Record({
    'prescription' : IDL.Text,
    'leftEyeAcuity' : IDL.Text,
    'optometrist' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'examDate' : IDL.Int,
    'rightEyeAcuity' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVitalReading' : IDL.Func([VitalReading], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVitalReading' : IDL.Func([IDL.Int], [], []),
    'getAllVitalReadings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VitalReading)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInsuranceInfo' : IDL.Func([IDL.Principal], [InsuranceInfo], ['query']),
    'getLatestVitalReading' : IDL.Func(
        [IDL.Principal, VitalType],
        [VitalReading],
        ['query'],
      ),
    'getMedicalHistory' : IDL.Func(
        [IDL.Principal],
        [MedicalHistory],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisionRecord' : IDL.Func([IDL.Principal], [VisionRecord], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInsuranceInfo' : IDL.Func([InsuranceInfo], [], []),
    'updateMedicalHistory' : IDL.Func([MedicalHistory], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
    'updateVisionRecord' : IDL.Func([VisionRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };