/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InsuranceInfo {
    primaryCarePhysician: string;
    groupNumber: string;
    medicareId: string;
    emergencyContacts: Array<EmergencyContact>;
    providerName: string;
    policyNumber: string;
}
export interface MedicalHistory {
    surgeries: Array<string>;
    vaccinations: Array<Vaccination>;
    diagnoses: Array<string>;
    medications: Array<Medication>;
    allergies: Array<string>;
}
export interface EmergencyContact {
    name: string;
    phone: string;
}
export interface Vaccination {
    date: bigint;
    name: string;
}
export interface VisionRecord {
    prescription: string;
    leftEyeAcuity: string;
    optometrist: string;
    notes?: string;
    examDate: bigint;
    rightEyeAcuity: string;
}
export interface VitalReading {
    readingType: VitalType;
    value: string;
    note?: string;
    unit: string;
    timestamp: bigint;
}
export interface UserProfile {
    bloodType: BloodType;
    dateOfBirth: bigint;
    name: string;
    primaryLanguage: string;
}
export interface Medication {
    dosage: string;
    name: string;
    frequency: string;
}
export enum BloodType {
    aNegative = "aNegative",
    oPositive = "oPositive",
    abPositive = "abPositive",
    bPositive = "bPositive",
    aPositive = "aPositive",
    oNegative = "oNegative",
    abNegative = "abNegative",
    bNegative = "bNegative"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VitalType {
    weight = "weight",
    bloodGlucose = "bloodGlucose",
    SpO2 = "SpO2",
    temperature = "temperature",
    bloodPressure = "bloodPressure",
    heartRate = "heartRate"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addVitalReading(reading: VitalReading): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteVitalReading(timestamp: bigint): Promise<void>;
    getAllVitalReadings(user: Principal): Promise<Array<VitalReading>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInsuranceInfo(user: Principal): Promise<InsuranceInfo>;
    getLatestVitalReading(user: Principal, vitalType: VitalType): Promise<VitalReading>;
    getMedicalHistory(user: Principal): Promise<MedicalHistory>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisionRecord(user: Principal): Promise<VisionRecord>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateInsuranceInfo(info: InsuranceInfo): Promise<void>;
    updateMedicalHistory(history: MedicalHistory): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
    updateVisionRecord(record: VisionRecord): Promise<void>;
}
import type { BloodType as _BloodType, UserProfile as _UserProfile, UserRole as _UserRole, VisionRecord as _VisionRecord, VitalReading as _VitalReading, VitalType as _VitalType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addVitalReading(arg0: VitalReading): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVitalReading(to_candid_VitalReading_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVitalReading(to_candid_VitalReading_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteVitalReading(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVitalReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVitalReading(arg0);
            return result;
        }
    }
    async getAllVitalReadings(arg0: Principal): Promise<Array<VitalReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVitalReadings(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVitalReadings(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsuranceInfo(arg0: Principal): Promise<InsuranceInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsuranceInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsuranceInfo(arg0);
            return result;
        }
    }
    async getLatestVitalReading(arg0: Principal, arg1: VitalType): Promise<VitalReading> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestVitalReading(arg0, to_candid_VitalType_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_VitalReading_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestVitalReading(arg0, to_candid_VitalType_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_VitalReading_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicalHistory(arg0: Principal): Promise<MedicalHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalHistory(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisionRecord(arg0: Principal): Promise<VisionRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisionRecord(arg0);
                return from_candid_VisionRecord_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisionRecord(arg0);
            return from_candid_VisionRecord_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInsuranceInfo(arg0: InsuranceInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInsuranceInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInsuranceInfo(arg0);
            return result;
        }
    }
    async updateMedicalHistory(arg0: MedicalHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicalHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicalHistory(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVisionRecord(arg0: VisionRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisionRecord(to_candid_VisionRecord_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisionRecord(to_candid_VisionRecord_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BloodType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodType): BloodType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_VisionRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisionRecord): VisionRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_VitalReading_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VitalReading): VitalReading {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_VitalType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VitalType): VitalType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bloodType: _BloodType;
    dateOfBirth: bigint;
    name: string;
    primaryLanguage: string;
}): {
    bloodType: BloodType;
    dateOfBirth: bigint;
    name: string;
    primaryLanguage: string;
} {
    return {
        bloodType: from_candid_BloodType_n16(_uploadFile, _downloadFile, value.bloodType),
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        primaryLanguage: value.primaryLanguage
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prescription: string;
    leftEyeAcuity: string;
    optometrist: string;
    notes: [] | [string];
    examDate: bigint;
    rightEyeAcuity: string;
}): {
    prescription: string;
    leftEyeAcuity: string;
    optometrist: string;
    notes?: string;
    examDate: bigint;
    rightEyeAcuity: string;
} {
    return {
        prescription: value.prescription,
        leftEyeAcuity: value.leftEyeAcuity,
        optometrist: value.optometrist,
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes)),
        examDate: value.examDate,
        rightEyeAcuity: value.rightEyeAcuity
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    readingType: _VitalType;
    value: string;
    note: [] | [string];
    unit: string;
    timestamp: bigint;
}): {
    readingType: VitalType;
    value: string;
    note?: string;
    unit: string;
    timestamp: bigint;
} {
    return {
        readingType: from_candid_VitalType_n10(_uploadFile, _downloadFile, value.readingType),
        value: value.value,
        note: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.note)),
        unit: value.unit,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: null;
} | {
    bloodGlucose: null;
} | {
    SpO2: null;
} | {
    temperature: null;
} | {
    bloodPressure: null;
} | {
    heartRate: null;
}): VitalType {
    return "weight" in value ? VitalType.weight : "bloodGlucose" in value ? VitalType.bloodGlucose : "SpO2" in value ? VitalType.SpO2 : "temperature" in value ? VitalType.temperature : "bloodPressure" in value ? VitalType.bloodPressure : "heartRate" in value ? VitalType.heartRate : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
}): BloodType {
    return "aNegative" in value ? BloodType.aNegative : "oPositive" in value ? BloodType.oPositive : "abPositive" in value ? BloodType.abPositive : "bPositive" in value ? BloodType.bPositive : "aPositive" in value ? BloodType.aPositive : "oNegative" in value ? BloodType.oNegative : "abNegative" in value ? BloodType.abNegative : "bNegative" in value ? BloodType.bNegative : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VitalReading>): Array<VitalReading> {
    return value.map((x)=>from_candid_VitalReading_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BloodType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodType): _BloodType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_VisionRecord_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisionRecord): _VisionRecord {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_VitalReading_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VitalReading): _VitalReading {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VitalType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VitalType): _VitalType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    readingType: VitalType;
    value: string;
    note?: string;
    unit: string;
    timestamp: bigint;
}): {
    readingType: _VitalType;
    value: string;
    note: [] | [string];
    unit: string;
    timestamp: bigint;
} {
    return {
        readingType: to_candid_VitalType_n3(_uploadFile, _downloadFile, value.readingType),
        value: value.value,
        note: value.note ? candid_some(value.note) : candid_none(),
        unit: value.unit,
        timestamp: value.timestamp
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bloodType: BloodType;
    dateOfBirth: bigint;
    name: string;
    primaryLanguage: string;
}): {
    bloodType: _BloodType;
    dateOfBirth: bigint;
    name: string;
    primaryLanguage: string;
} {
    return {
        bloodType: to_candid_BloodType_n24(_uploadFile, _downloadFile, value.bloodType),
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        primaryLanguage: value.primaryLanguage
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prescription: string;
    leftEyeAcuity: string;
    optometrist: string;
    notes?: string;
    examDate: bigint;
    rightEyeAcuity: string;
}): {
    prescription: string;
    leftEyeAcuity: string;
    optometrist: string;
    notes: [] | [string];
    examDate: bigint;
    rightEyeAcuity: string;
} {
    return {
        prescription: value.prescription,
        leftEyeAcuity: value.leftEyeAcuity,
        optometrist: value.optometrist,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        examDate: value.examDate,
        rightEyeAcuity: value.rightEyeAcuity
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodType): {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
} {
    return value == BloodType.aNegative ? {
        aNegative: null
    } : value == BloodType.oPositive ? {
        oPositive: null
    } : value == BloodType.abPositive ? {
        abPositive: null
    } : value == BloodType.bPositive ? {
        bPositive: null
    } : value == BloodType.aPositive ? {
        aPositive: null
    } : value == BloodType.oNegative ? {
        oNegative: null
    } : value == BloodType.abNegative ? {
        abNegative: null
    } : value == BloodType.bNegative ? {
        bNegative: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VitalType): {
    weight: null;
} | {
    bloodGlucose: null;
} | {
    SpO2: null;
} | {
    temperature: null;
} | {
    bloodPressure: null;
} | {
    heartRate: null;
} {
    return value == VitalType.weight ? {
        weight: null
    } : value == VitalType.bloodGlucose ? {
        bloodGlucose: null
    } : value == VitalType.SpO2 ? {
        SpO2: null
    } : value == VitalType.temperature ? {
        temperature: null
    } : value == VitalType.bloodPressure ? {
        bloodPressure: null
    } : value == VitalType.heartRate ? {
        heartRate: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
